matrix:
  include:
    - os: linux
      arch: amd64
      dist: focal
      compiler: gcc
      addons:
        apt:
          packages:
            - bc
            - samtools
            - parallel
            - meson
            - ninja-build
    - os: linux
      arch: ppc64le
      dist: focal
      compiler: gcc
      addons:
        apt:
          packages:
            - bc
            - samtools
            - parallel
            - meson
            - ninja-build
     

script:
  - apt-cache pkgnames|grep hts|grep lib
  - mkdir build
  - meson build/
  - ninja -C build/
  - meson test --timeout-multiplier 8 -C build/
  - [ $? != 0 ] && cat /home/travis/build/freebayes/freebayes/build/meson-logs/testlog.txt
